package generator

import (
	"fmt"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"
	"log"
	"strings"
)

type endpointGenerator struct {
	*Generator
	gen  *protogen.Plugin
	file *protogen.File
	g    *protogen.GeneratedFile
}

// GenerateFileContent generates the gRPC service definitions, excluding the package statement.
func (m endpointGenerator) GenerateFileContent() {
	if len(m.file.Services) == 0 {
		return
	}

	for _, service := range m.file.Services {
		if GetIsEndpointExtensionFor(service.Desc.Options()) {
			m.genService(service)
		}
	}
}

func (m endpointGenerator) genService(service *protogen.Service) {

	m.g.Unskip()

	m.genImpl(service)
	m.genConstructor(service)
	m.genDefinition(service)

	for _, method := range service.Methods {
		m.genMethodHandler(service, method)
	}
}

func (m endpointGenerator) genHeader(packageName string) {
	m.g.P("// Code generated by protoc-gen-go-ras. DO NOT EDIT.")
	m.g.P()
	m.g.P("package ", packageName)
	m.g.P()
}
func (m endpointGenerator) genImpl(service *protogen.Service) {

	log.Println(m.idxImpl)

	m.g.P("type ", m.getClientImp(service), " interface {")
	for _, method := range service.Methods {
		m.g.P("", method.GoName, m.genMethodSig(method))
	}
	m.g.P("}")

	m.AddImpl(m.getClientImp(service), protogen.GoImportPath(m.file.GoPackageName))

}

func (m endpointGenerator) genMethodSig(method *protogen.Method) string {

	ext := GetClientMethodExtensionFor(method.Desc.Options())

	inParam := ""
	outParam := "(*" + m.g.QualifiedGoIdent(method.Output.GoIdent) + ", error)"
	if len(ext.MethodParams) > 0 {

		var p []string
		for varName, varValue := range ext.MethodParams {
			p = append(p, fmt.Sprintf("%s %s", varName, m.g.QualifiedGoIdent(m.GetImpl(varValue))))
		}

		inParam = strings.Join(p, ", ")
	}

	if ext.IgnoreEmpty {
		outParam = "error"
	}

	return fmt.Sprintf("(%s) %s", inParam, outParam)
}

func (m endpointGenerator) genConstructor(service *protogen.Service) {
	clientServiceImpl := m.GetImpl("ClientServiceImpl")
	serviceName := m.getClientName(service)

	m.g.P("func New", serviceName, "(clientService ", clientServiceImpl, ", version int32) ", m.getClientImp(service), "{")
	m.g.P("return &", serviceName, "{")
	m.g.P("client: clientService,")
	m.g.P("Version: version,")
	m.g.P("}")
	m.g.P("}")

}

func (m endpointGenerator) genDefinition(service *protogen.Service) {
	serviceName := m.getClientName(service)
	clientServiceImpl := m.GetImpl("ClientServiceImpl")

	m.g.P("// ", serviceName, " is the endpoint service for RAS service.")
	if service.Desc.Options().(*descriptorpb.ServiceOptions).GetDeprecated() {
		m.g.P("//")
		m.g.P(deprecationComment)
	}
	m.g.Annotate(serviceName, service.Location)
	m.g.P("type ", serviceName, " struct {")
	m.g.P("client ", clientServiceImpl, "")
	m.g.P("Version int32")
	m.g.P("}")
	m.g.P()
}

func (m endpointGenerator) genClientOptionsDefinition(service *protogen.Service) {
	// Server registration.
	if service.Desc.Options().(*descriptorpb.ServiceOptions).GetDeprecated() {
		m.g.P(deprecationComment)
	}
	optionName := m.getClientOptionName(service)
	optionsName := m.getClientOptionsName(service)
	m.g.P("type ", optionName, " func(*", optionsName, ")")
	m.g.P()
	m.g.P("type ", optionsName, " struct {")
	m.g.P("dialer *", netPackage.Ident("Dialer"), "")
	m.g.P("}")
	m.g.P()
	m.g.P("func WithDialer(dialer *", netPackage.Ident("Dialer"), ") ", optionName, " {")
	m.g.P("return func (o *", optionsName, ") { o.dialer = dialer }")
	m.g.P("}")

}

func (m endpointGenerator) genDialMethodFunction(service *protogen.Service) {
	m.g.P("func (x *", m.getClientName(service), ") dial() error {")
	m.g.P("if x.conn != nil { return nil }")
	m.g.P("if _, err :=", netPackage.Ident("ResolveTCPAddr"), "(\"tcp\", x.host); err != nil { return err }")
	m.g.P()
	m.g.P("var err error")
	m.g.P("if x.dialer != nil { ")
	m.g.P("x.conn, err = x.dialer.Dial(\"tcp\", x.host)")
	m.g.P("return err")
	m.g.P("}")
	m.g.P("x.conn, err = ", netPackage.Ident("Dial"), "(\"tcp\", x.host)")
	m.g.P("return err")
	m.g.P("}")
	m.g.P()
}

func isEmptyPb(m protoreflect.MessageDescriptor) bool {
	return m.FullName() == "google.protobuf.Empty"
}
func (m endpointGenerator) genMethodHandler(service *protogen.Service, method *protogen.Method) {
	ext := GetClientMethodExtensionFor(method.Desc.Options())

	m.g.P("func (x *", m.getClientName(service), ") ", method.GoName, "(req *", method.Input.GoIdent, ") (*", method.Output.GoIdent, ", error) {")
	m.g.P("if err := x.dial(); err != nil { return nil, err }")
	if ext.NoPacketPack {
		m.g.P("// TODO convert to formatter")
		m.g.P("if err := req.", m.formatFuncName, "(x.conn, 0 ); err != nil { return nil, err }")
	} else {
		m.g.P("packet, err := ", method.Input.GoIdent.GoImportPath.Ident("NewPacket"), "(req)")
		m.g.P("if err != nil { return nil, err }")
		m.g.P("if _, err := packet.WriteTo(x.conn); err != nil { return nil, err }")
	}
	if isEmptyPb(method.Output.Desc) {
		m.g.P("return new(", method.Output.GoIdent, "), nil")
		m.g.P("}")
		return
	}
	m.g.P("if err := x.conn.SetReadDeadline(time.Now().Add(5 * ", timePackage.Ident("Second"), ")); err != nil { return nil, err }")
	m.g.P("ackPacket, err := ", method.Input.GoIdent.GoImportPath.Ident("NewPacket"), "(x.conn)")
	m.g.P("if err != nil { return nil, err }")
	m.g.P("resp := new(", method.Output.GoIdent, ")")
	m.g.P("return resp, ackPacket.Unpack(resp)")
	m.g.P("}")
	m.g.P()
}

func (m endpointGenerator) getClientName(service *protogen.Service) string {
	return service.GoName
}

func (m endpointGenerator) getClientImp(service *protogen.Service) string {
	return service.GoName + "Impl"
}

func (m endpointGenerator) getClientOptionsName(service *protogen.Service) string {
	return service.GoName + "Options"
}

func (m endpointGenerator) getClientOptionName(service *protogen.Service) string {
	return service.GoName + "Option"
}
