package generator

import (
	"google.golang.org/protobuf/compiler/protogen"
	"strings"
)

func (gen *Generator) generatePacketHelpers(g *protogen.GeneratedFile, m *protogen.Message) {

	packetTypeIdent := gen.EnumNamed("PACKET_TYPE_NEGOTIATE").TypeIdent
	messageName := m.GoIdent.GoName + "Message"
	messageFormatterName := messageName + "Formatter"
	messageParserName := messageName + "Parser"

	g.P("// Helpers generated by github.com/v8platform/protoc-gen-go-ras. DO NOT EDIT")
	g.P("type ", messageName, " interface {")
	g.P(" ", messageFormatterName)
	g.P(" ", messageParserName)
	g.P("}")
	g.P()
	g.P("type ", messageFormatterName, " interface {")
	g.P(" GetPacketType() ", g.QualifiedGoIdent(packetTypeIdent))
	g.P(" ", gen.formatFuncName, "(writer io.Writer, version int32) error")
	g.P("}")
	g.P()
	g.P("type ", messageParserName, " interface {")
	g.P(" GetPacketType() ", g.QualifiedGoIdent(packetTypeIdent))
	g.P(" ", gen.parseFuncName, "(reader io.Reader, version int32) error")
	g.P("}")
	g.P()
	g.Annotate(m.GoIdent.GoName, m.Location)
	g.P("func New", m.GoIdent.GoName, "(message ", m.GoIdent.GoName, "MessageFormatter) (*", m.GoIdent, ", error){")
	g.P("buf := &", bytesBuffer, "{}")
	g.P("if err := message.", gen.formatFuncName, "(buf, 0); err != nil { return nil, err }")
	g.P("var packet ", m.GoIdent, "")
	g.P("packet.Type = message.GetPacketType()")
	g.P("packet.Data = buf.Bytes()")
	g.P("packet.Size = int32(len(packet.Data))")
	g.P("return &packet,  nil")
	g.P("}")
	g.P()
	g.Annotate(m.GoIdent.GoName, m.Location)
	g.P("func (x *", m.GoIdent, ") Unpack(into ", messageParserName, ") error {")
	g.P("if x.GetType() != into.GetPacketType() {")
	g.P("return ", fmtErrorf, "(\"unpack type no equal packet type. Has %s want %s\", into.GetPacketType(), x.GetType())")
	g.P("}")
	g.P("buf := ", bytesNewBuffer, "(x.Data)")
	g.P("return into.Parse(buf, 0)")
	g.P("}")
	g.P()
	g.Annotate(m.GoIdent.GoName, m.Location)
	g.P("func (x *", m.GoIdent, ") UnpackNew() (", messageName, ", error) {")
	g.P("var into ", messageName)
	g.P("switch x.GetType() {")

	for enumName, object := range gen.enumToObject {
		if strings.HasPrefix(enumName, "PACKET_TYPE") {
			enumIdent := gen.EnumNamed(enumName)
			g.P("// type ", enumIdent.GoName, " cast ", object.GoName)
			g.P("case ", enumIdent.GoIdent, " :")
			g.P("into = &", object.GoIdent, "{}")
		}
	}

	g.P("default: ")
	g.P("return nil, ", fmtErrorf, "(\"unknown unpack type %s\",  x.GetType())")
	g.P("}")
	g.P("buf := ", bytesNewBuffer, "(x.Data)")
	g.P("if err := into.Parse(buf, 0); err != nil { return nil, err }")
	g.P("return into, nil")
	g.P("}")
	g.P()
	g.Unskip()
}

var tpl = `




`
