project_name: protoc-gen-go-ras

env:
  - GO111MODULE=on
before:
  hooks:
    - rm tests/client_test.go
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64

dist: dist

checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
dockers:
  - image_templates:
      - 'v8platform/{{.ProjectName}}:{{ .Tag }}'
      - 'v8platform/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}'
      - 'v8platform/{{.ProjectName}}:latest'
      - 'ghcr.io/v8platform/{{.ProjectName}}:{{ .Tag }}'
      - 'ghcr.io/v8platform/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}'
      - 'ghcr.io/v8platform/{{.ProjectName}}:latest'
      - 'plugins.buf.build/v8platform/{{.ProjectName}}:{{ .Tag }}'
      - 'plugins.buf.build/v8platform/{{.ProjectName}}:v{{ .Major }}.{{ .Minor }}'
    dockerfile: Dockerfile
    ids:
      - protoc-gen-go-ras
    build_flag_templates:
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"
      - "--label=com.github.actions.name={{.ProjectName}}"
      - "--label=com.github.actions.description=Plugin for Protoc to generate RAS modules"
      - "--label=com.github.actions.icon=terminal"
      - "--label=com.github.actions.color=blue"
      - "--label=repository=http://github.com/v8platform/protoc-gen-go-ras"
      - "--label=homepage=http://github.com/v8platform/protoc-gen-go-ras"
      - "--label=maintainer=Aleksey Khorev <khorevaa@gmail.com>"
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

